export { SELECT_ACCOUNT, SELECT_LIST_ACCOUNT } from 'tables/accounts/queries'
export { SELECT_PLACE, SELECT_LIST_PLACE } from 'tables/places/queries'
export { SELECT_EVENT, SELECT_LIST_EVENT } from 'tables/events/queries'
export { SELECT_EVENT_MEMBER, SELECT_LIST_EVENT_MEMBER } from 'tables/event_members/queries'
export { SELECT_PERSON_IN_GROUP, SELECT_LIST_PERSON_IN_GROUP } from 'tables/person_in_groups/queries'
export { SELECT_TIMETABLE, SELECT_LIST_TIMETABLE } from 'tables/timetables/queries'
export { SELECT_GROUP_OF_PEOPLE, SELECT_LIST_GROUP_OF_PEOPLE } from 'tables/group_of_people/queries'
export { SELECT_PERSON, SELECT_LIST_PERSON } from 'tables/people/queries'
